### PR TITLE
Use `rollup-plugin-babel` to transpile code

### PR DESCRIPTION
**Pull request by dgdavid**
Related to #36 and #33, this PR allow to build library transpiled.

Since `dist` folder is being ignored by Git, its changes are not included here. I tried to follow the project style using available scripts.

- `yarn clean` ✔️ 
- `yarn lint` ✔️   
- `yarn build` ✔️ 
- `yarn commit` ✔️ 
-  `yarn test` ❌  _(do nothing)_
-  `yarn release` ❌

### CODE REVIEW

**Comment by dgdavid** [comment]
Just a friendly ping, @jhabdas

**Comment by JamiesonRoberts** [comment]
@dgdavid I can't speak for @jhabdas , but given that he hasn't committed other lock files, convention would dictate that you don't commit the yarn one either.

**Comment by jhabdas** [comment]
hi @dgdavid. not gonna lie didn't see this till now. sorry for the delay. purposely avoided Babel in design to prevent maintenance and breaking changes. tbh Babel is one of the reasons I started disliking JavaScript. sorry again for the slow response

**Comment by jhabdas** [comment]
@JamiesonRoberts dead on I don't see a need for lock files for dev deps this light

**Comment by dgdavid** [comment]
@JamiesonRoberts,

I must admit that I didn't realize.

So, thank you for the note, which I am sure will be useful for me in future PR.

**Comment by jhabdas** [comment]
@JamiesonRoberts @dgdavid  totally changed my mind about the lock file now that it's advanced far enough to allow easy conflict resolution (my primary hangup with it before):

https://docs.npmjs.com/files/package-locks#resolving-lockfile-conflicts

As a result I will be adding the lockfile to help users gain the advantage of a repeatable build process in case one of the dev deps does a bad semver.

**Pull request closed without merging**
